version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-3542}:3542"
    volumes:
      - ./apps/backend/data:/app/data
      - ./apps/backend/temp:/app/temp
      - ./public:/app/public
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3542
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=${API_URL:-http://backend:3542}
      - SHOW_TEST_BUTTON=${SHOW_TEST_BUTTON:-false}
    depends_on:
      - backend
    restart: unless-stopped 